---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: project1-app
  namespace: default
  labels:
    app: project-1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: project-1
  template:
    metadata:
      labels:
        app: project-1
    spec:
      containers:
      - name: project-cont
        image: "bharathsharath/project-1:latest"
        ports:
          - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: project-1-app
  namespace: default
spec:
  selector:
    app: project-1
  type: LoadBalancer
  ports:
  - name: http
    targetPort: 8080
    port: 8080
    nodePort: 31113
